# Generated by Django 3.2.23 on 2024-03-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionalAdvice',
            fields=[
                ('score', models.FloatField(primary_key=True, serialize=False)),
                ('advice', models.TextField()),
            ],
        ),
    ]
