# Generated by Django 3.2.23 on 2024-03-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sentiment', models.CharField(max_length=20)),
                ('sentiment_score', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='EmotionalAdvice',
        ),
    ]
