# Generated by Django 3.2.23 on 2024-03-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('emotion', models.CharField(max_length=50)),
                ('sentiment', models.CharField(max_length=20)),
                ('emoji', models.CharField(max_length=10)),
            ],
        ),
    ]
